#%RAML 1.0 NamedExample
  status: "partial success"
  message: "Request has been partially processed successfully"
  inventory:
    - inventoryId: 1
      upcCode: "608270030"
      websiteId: "13801"
      fulfillmentCenterId: 0 
      availableFlag: "1"
      qtyAvailable: 2739
      dateAvailable: "2020-04-16" 
      nextShipDate: "2020-04-16"
      nextShipQty: 0
      createdDate: "2015-07-04T21:00:00"
      error: "Truncate error"